app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('setup/', views.SetupView.as_view(), name='setup'),
    path('result/', views.ResultView.as_view(), name='result'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator


class IndexForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control' # bootstrapを使用するため
            field.widget.attrs['placeholder'] = field.label

    username = forms.CharField(label='ユーザー名')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput(), min_length=8)


class SetupForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

    url = forms.CharField(label='属性が近いユーザのURL')

    max_like_count = forms.IntegerField(label='いいねする数', validators=[MinValueValidator(1)])

app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .forms import IndexForm, SetupForm
from .like.like import AutoLiker


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = IndexForm()
        return context


class SetupView(TemplateView):
    template_name = 'setup.html'

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SetupForm()

        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SetupForm()

        form = IndexForm(request.POST)
        if form.is_valid():
            d = form.cleaned_data
            request.session['username'] = d.get('username')
            request.session['password'] = d.get('password')

        return self.render_to_response(context)


class ResultView(TemplateView):
    template_name = 'result.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        form = SetupForm(request.POST)
        if form.is_valid():
            d = form.cleaned_data
            request.session['url'] = d.get('url')

            # 自動いいね

            autoliker = AutoLiker()
            autoliker.set_account(username=request.session.get('username'), password=request.session.get('password'))
            autoliker.set_url(url=d.get('url'), max_like_count=d.get('max_like_count'))

            # 結果を返す
            context['result'] = autoliker.start()

        return self.render_to_response(context)

templates/base.html
{% load i18n static %}

<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
{% block extra_css %}{% endblock %}
<title>{% block title %}Instagramいいねツール{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h3 class="text-center my-4">Instagramのアカウントを入力してください</h3>
<form action="{% url 'app:setup' %}" method="post">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                {% for field in form %}
                    {{ field }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ハッシュタグを選択する</button>
                {% csrf_token %}
            </div>
        </div>
    </div>
</form>
{% endblock content %}

templates/result.html
{% extends "base.html" %}

{% block content %}
{% if result  %}
<h3 class="text-center my-4">いいねの結果</h3>
<table class="table table-striped">
    <tr><td>対象のURL</td><td>{{ result.url }}</td></tr>
    <tr><td>成功いいね数</td><td>{{ result.like_count }}</td></tr>
</table>
{% else %}
<h3 class="text-center my-4">いいねに失敗しました。通信状況等を確認してください</h3>
<div class="text-center">
	<a href="{% url 'app:index' %}" class="btn btn-outline-info mr-3" role="button">やり直す</a>
</div>
{% endif %}

{% endblock content %}

templates/setup.html
{% extends "base.html" %}

{% block content %}
<h3 class="text-center my-4">属性の近いユーザのURLを入植してください（いいねが多いユーザ推奨）</h3>
<form action="{% url 'app:result' %}" method="post">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                {% for field in form %}
                    {{ field }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >いいねを実行する</button>
                {% csrf_token %}
            </div>
        </div>
    </div>
</form>
{% endblock content %}